var mongoose = require('mongoose');  
var questionsSchema = new mongoose.Schema({  
	questionId : String,  
	userId:String,
	groupId:String,
	questionType: String,
	questionText : String, 
	language:String,
	categoryName : String,
	groupName: String,
	status: String,
	answers: String,
	queStatus:String,
	upVote : Number,
	comments: String,
	postedBy:String,
	reply: String,
	createdDate : Date, 
	updatedDate : Date,
	userGroupId : String,
	userImage:String,
	answerCount:String,
	location:String,
	anonymFlage:String,
	questionLink:String,
	upVoted:Array,
	likeImage: String,
	likeBlueImage:String,
	likeFlag:String,
	ansUserImage:String,
	ansUserName:String,
	ansUserId:String,
	ansDate:Date,
	compliance:String,
	mlprocess:String,
	LikeArray:Array
});
mongoose.model('questions', questionsSchema,'questions');