var mongoose = require('mongoose');  
var usersSchema = new mongoose.Schema({  
	userId:String,
	userName :String,
	email: String,
	password:String,
	certification:String,
	department: String,
	mobileNo: String,
	OTP:String,
	usercredit:Number,
	queCount:Number,
	ansCount:Number,
	expertIn:Array,
	articalCount:Number,
	language:String,
	notificationFlag:Boolean,
	emailVerified:Boolean,
	subscripExpDate:String,
	userImage:String,
	level:String,
	userType:String,
	status:String,
	userStatus:String,
	createdDate: Date,
	updatedDate: Date,
	socialId : String,
	userName:String,
	firstName : String,
	lastName : String,
	gender : String,
	provider:String,
	following:Array,
	followers:Array,
	followingGroups:Array,
	bookMarkCategory:Array,
	arrUserBlocked:Array,
	userGroupId : String,

	// for add credential
	college : String,
	address: String,
	education:String,
	articles: Number,
	work:String,
	topicInterest:String,
	designation:String,
    companyName : String,
    position : String,
    startYear : String,
    endYear : String,
    graduationYear:String,
	degreeType : String,
	locationStartYear : String,
	locationEndYear : String,
	currentWork : String,
	defaultLanguage : String,
	specialization : String,


});
mongoose.model('users', usersSchema,'users');
